# Generated by Django 3.2.6 on 2021-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_thread_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
    ]
