version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8010:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env/.dev-sample
    networks:
      - elastic
    depends_on:
      - redis
      - db
      - elasticsearch

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=db_gg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nepeizarulem02
    

  redis:
    image: redis:5-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celey_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
      
  # elasticsearch:
    # build:
    #   context: .
    #   dockerfile: ./compose/local/django/Dockerfile
    # image: elasticsearch:7.4.0
    # volumes:
    #   - .:/app
    # env_file:
    #   - ./.env/.dev-sample
    # ports:
    #   - "9200:9200"
    # depends_on:
    #   - redis
    #   - db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - vibhuviesdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    labels:
      - co.elastic.logs/module=elasticsearch
      - co.elastic.metrics/module=elasticsearch
networks:
  elastic:
    driver: bridge 
volumes:
  postgres_data:
  vibhuviesdata:
      driver: local